### ISSUE TITLE
Last update inserted compatibility issue with Jules&Ben's Animated Assets

### ISSUE THREAD

**Issue by nulmas** [theripper93/dnd-randomizer#24]
With the last update, the generator simply won't work if Jules&Ben's Animated Assets is also active in the world. It stays stuck trying to generate encounters.

If JB2A is deactivated, it works as intended. I also rolled back to the previous version of Stochastic, Fantastic! to check if I wasn't wrong, and it works normally even if JB2A is active.

The issue happened with the Free version of JB2A, I haven't been able to check with the Patreon version yet.

EDIT: This happened using the DnD 5e system.

**Comment by theripper93** [comment]
I’m assuming they have compendiums with items or monsters, try to exclude those

**Comment by nulmas** [comment]
> > I’m assuming they have compendiums with items or monsters, try to exclude those

That works, thank you! They don't really include any monsters, but there's a list of actors for the animations.

**Comment by nulmas** [comment]
@theripper93 - Just to let you know that this last update fixed this issue.
