### ISSUE TITLE
Not showing ENVIRONMENT option

### ISSUE THREAD

**Issue by rbl047** [theripper93/dnd-randomizer#36]
I've just changed my Foundry to V.9 and realized the Stochastic, Fantastic! Encounter Generator module is not showing the "environment option" anymore. 
Any help with that? Thanks!
![image](https://user-images.githubusercontent.com/46825122/159350642-9e604605-6d8c-4e9b-b8f7-9e59d662f61d.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
