### ISSUE TITLE
Spawning Issue

### ISSUE THREAD

**Issue by dangerdaren** [theripper93/dnd-randomizer#9]
This seems like a fantastic module, but on testing it, I'm running into an issue where if I hit Spawn Encounter, it won't spawn unless I draw the circle in a single square--anything more it won't spawn. Also, when i choose a new encounter to spawn and draw the circle, it will spawn a previous encounter, not the one I chose. I'm running 5e version 1.4.3 on FVTT version 0.8.9 on Chrome. Perhaps it is interfering with another module? I'll play with it, but wanted to see if this is a known issue. Looking forward to using this, if even just by dragging the creatures onto the map. Nice work!

**Comment by theripper93** [comment]
Not a known issue, check wiht other mods disabled and report back please
